#!/usr/bin/env bash

# Remove whiptail and install both Python 2 and 3

PY2=1
PY3=1

# Install required packages
apt-get install git bc i2c-tools fonts-freefont-ttf whiptail make gcc -y
if [ $PY2 -eq 1 ]; then
   apt-get install python-pil python-smbus python-dateutil -y
fi
if [ $PY3 -eq 1 ]; then
   apt-get install python3-pil python3-smbus python3-dateutil -y
fi

# Enable SPI and I2C
raspi-config nonint do_spi 0
raspi-config nonint do_i2c 0

# Clone GitHub Repo from @21iseough with slight changes
git clone --depth=1 https://github.com/21isenough/PaPiRus.git
cd PaPiRus

# Install Papirus Python library for Python 2 and/or 3
if [ $PY2 -eq 1 ]; then
   python setup.py install
fi
if [ $PY3 -eq 1 ]; then
   python3 setup.py install
fi

# Install drivers and setup epaper
papirus-setup

# Remove whiptail, reboot later
